/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/crystal_spinner-transformed.glb --types --shadows -o src/components/CrystalSpinnerModel.tsx 
Author: Chaitanya Krishnan (https://sketchfab.com/chaitanyak)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/crystal-spinner-302490fa64314beca7929b1c4e35229a
Title: Crystal Spinner
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    crystal1: THREE.MeshStandardMaterial
    crystal2: THREE.MeshStandardMaterial
    crystal3: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/crystal_spinner-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Cube_0" rotation={[0.975, -0.801, 0.032]} scale={0.468}>
            <mesh name="Object_4" castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.crystal1} />
          </group>
          <group name="Cube001_3" rotation={[0.719, -0.507, -0.38]} scale={0.738}>
            <mesh name="Object_6" castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.crystal2} />
          </group>
          <group name="Cube002_4" rotation={[-0.025, -0.614, -2.353]} scale={0.738}>
            <mesh name="Object_8" castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.crystal3} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/crystal_spinner-transformed.glb')
